# Generated by Django 5.2.4 on 2025-08-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0003_campaignapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignapp',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
